name: news_sentiment
channels:
  - defaults
dependencies:
  - python=3.10
  - numpy==1.21.5
  - pandas==1.4.4
  - pip==23.2.1
  - pip:
    - fastapi==0.68.0
    - uvicorn==0.15.0
    - gunicorn==21.2.0
    - aiofiles==23.2.1
    - requests==2.31.0
    - openai==1.3.5